import "@/ui/globals.css";
import { poppins } from "@/ui/fonts";
import Navbar from "@/ui/navbar/navbar";

export const metadata = {
  title: "NeuraQuery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
